# Generated by Django 3.2 on 2022-05-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
